### ISSUE TITLE
Target time ESS

### ISSUE THREAD

**Issue by sbeuvain** [draganignjic/timmi-ess-fusion#19]
Hi,
is it possible to add the target time ?

**Comment by draganignjic** [comment]
Hi. 

Yes it is possible. I removed it because for all employees in Switzerland it always showed 8.4 hours without considering part time employees. So to avoid showing wrong data I removed the field completely. 

You can comment out or delete Line 55 in the script to see it. (removeTargetHours())
What number do you see for your target time?

Regards,
Dragan

**Comment by sbeuvain** [comment]
Hi, thanks for the workaround.
In my case in France, the value is 7,40.
It is useful to see the public holidays because the value in this case is 0.
In this case, the ideal would be to change the color column to attract attention.

Regards,
Stéphane

**Comment by draganignjic** [comment]
I now reenabled the target times for all users.
